CREATE SCHEMA IF NOT EXISTS "spot_bot_vip";

CREATE TABLE IF NOT EXISTS roles (
     id SERIAL PRIMARY KEY,
     name VARCHAR(255) UNIQUE NOT NULL,
     owner_id VARCHAR(255) NOT NULL,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_invitations (
      id SERIAL PRIMARY KEY,
      role_id INTEGER REFERENCES roles(id),
      owner_id VARCHAR(255) NOT NULL,
      member_id VARCHAR(255) NOT NULL,
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);