version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: Spot-bot-Database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  postgres_data:
    driver: local
